### ISSUE TITLE
HeytingAlgebra instance

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-tuples#21]
@paf31 you mentioned in purescript/purescript-prelude#62 that `Tuple` is a `HeytingAlgebra`, is the [definition we have here](https://github.com/purescript/purescript-tuples/blob/v1.0.0-rc.2/src/Data/Tuple.purs#L91-L97) what you meant, or is there something cleverer/more useful than that?

**Comment by paf31** [comment]
Yes, that's the one. It just allows for multiple different interpretations of the Boolean operations at the same time, e.g. `Boolean` and `Interval`, or whatever.
