### ISSUE TITLE
Discussion: Convert Tuple into a newtyped Record

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript-tuples#32]
Is there any reason to use a `Tuple` instead of a `Record`?

I've heard a number of times to not use `Tuple` and instead use a `Record`. So, why not just newtype a `Record` so we can still have instances and call it a `Tuple`?
```purescript
newtype Tuple a b = Tuple { fst :: a, snd :: b }
```

**Comment by garyb** [comment]
Pretty sure the "hidden class" VM optimisation wouldn't trigger with this representation, that's why the data types in PS are represented the way they are in general.

**Comment by JordanMartinez** [comment]
Gotcha. Closing.
