### ISSUE TITLE
Add an operator for convenience

### ISSUE THREAD

**Issue by david-sledge** [purescript/purescript-tuples#53]
How about we have an operator (i recommend `*&` because it's a product type) to use as an alternative to the constructor. `a *& b` as alternative `Tuple a b`.

**Comment by natefaubion** [comment]
An operator is included in Data.Tuple.Nested
https://github.com/purescript/purescript-tuples/blob/4f52da2729b448c8564369378f1232d8d2dc1d8b/src/Data/Tuple/Nested.purs#L72

**Comment by david-sledge** [comment]
Geez... How did miss that?

**Comment by natefaubion** [comment]
Probably because it's in `Nested`, when it doesn't necessarily need to be 😄
